-- Age-group teams (U11, U12, and future). The club coaches (Veronica, Reece,
-- Josh) coach all teams, so there is intentionally no per-team coach assignment.
create table if not exists public.teams (
  id          integer generated by default as identity primary key,
  name        text not null,
  slug        text unique,
  description text,
  season      text,
  sort_order  integer default 0,
  active      boolean default true,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

alter table public.teams enable row level security;
create policy teams_read   on public.teams for select using (true);
create policy teams_insert on public.teams for insert with check (true);
create policy teams_update on public.teams for update using (true);
create policy teams_delete on public.teams for delete using (true);

-- Seed the two current teams (only if the table is empty).
insert into public.teams (name, slug, sort_order)
select v.name, v.slug, v.sort_order
from (values ('U11', 'u11', 1), ('U12', 'u12', 2)) as v(name, slug, sort_order)
where not exists (select 1 from public.teams);

-- Link players to a team (nullable — existing players start unassigned so the
-- coach can assign them from the roster editor).
alter table public.players add column if not exists team_id integer references public.teams(id) on delete set null;
create index if not exists players_team_id_idx on public.players (team_id);
