-- Non-sponsor fundraising income (water sales, donations, concessions, gate fees, etc.).
-- Kept separate from the sponsorships table so the public sponsor list stays clean.
-- Mirrors the shape/conventions of the existing public.expenses table.
create table if not exists public.income (
  id           integer generated by default as identity primary key,
  description  text not null,
  amount       numeric not null,
  category     text not null,
  source       text,                         -- who the money came from (payer/event)
  income_date  date not null default current_date,
  payment_method text default 'Cash',
  notes        text,
  season       text,
  created_by   text,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

create index if not exists income_income_date_idx on public.income (income_date);

alter table public.income enable row level security;

-- Match the existing expenses RLS convention (app enforces auth at the route layer).
create policy income_read   on public.income for select using (true);
create policy income_insert on public.income for insert with check (true);
create policy income_update on public.income for update using (true);
create policy income_delete on public.income for delete using (true);
