-- Log of morning-of SMS reminders sent for practices/games. The unique index
-- is the idempotency guard: if the cron route runs twice in a day (retry,
-- manual trigger), the second insert conflicts and we skip the send.
create table if not exists public.sms_reminder_log (
  id          integer generated by default as identity primary key,
  item_kind   text not null,            -- 'event' (practice) | 'game' (schedule row)
  item_id     bigint not null,
  remind_date date not null,            -- club-timezone day the reminder was for
  phone       text not null,            -- E.164 recipient
  sid         text,                     -- Twilio message SID
  created_at  timestamptz default now(),
  unique (item_kind, item_id, remind_date, phone)
);

-- Written only by the cron route via the service role key; no client access.
alter table public.sms_reminder_log enable row level security;
