-- Links an admin calendar row (a game or an event) to the GroupMe calendar
-- event created for it, per group.
--
-- Without this mapping every sync run would create duplicates: GroupMe's event
-- API has no idempotency key and no way to look an event up by our id.
--
-- `content_hash` lets a run tell "unchanged" from "edited" without diffing every
-- field, so an untouched fixture costs zero API calls.
--
-- `state` is 'active' or 'cancelled'. GroupMe exposes no delete endpoint (create
-- and update are reachable; every delete path shape returns a generic 500), so a
-- removed or cancelled fixture is *renamed* to mark it cancelled rather than
-- deleted. That is also kinder to anyone who already RSVP'd — the event stays
-- visible with its status changed instead of silently disappearing.
create table if not exists public.groupme_calendar_sync (
  id                 integer generated by default as identity primary key,
  item_kind          text not null,          -- 'event' | 'game'
  item_id            bigint not null,
  bot_key            text not null,          -- team id as text, or 'all'
  group_id           text not null,          -- GroupMe conversation id
  groupme_event_id   text not null,
  content_hash       text not null,
  state              text not null default 'active',
  created_at         timestamptz default now(),
  updated_at         timestamptz default now(),
  unique (item_kind, item_id, bot_key)
);

create index if not exists groupme_calendar_sync_item_idx
  on public.groupme_calendar_sync (item_kind, item_id);

-- Written only by the sync cron via the service role key; no client access.
alter table public.groupme_calendar_sync enable row level security;
