-- Per-game player stat lines, keyed to a scheduled game. Complements the
-- existing season-total player_stats; this is the game-by-game log.
create table if not exists public.game_stats (
  id           integer generated by default as identity primary key,
  schedule_id  bigint references public.schedule(id) on delete cascade,
  player_id    bigint references public.players(id) on delete cascade,
  goals        integer default 0,
  assists      integer default 0,
  yellow_cards integer default 0,
  red_cards    integer default 0,
  saves        integer default 0,
  clean_sheet  boolean default false,
  minutes      integer,
  note         text,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now(),
  unique (schedule_id, player_id)
);

create index if not exists game_stats_schedule_idx on public.game_stats (schedule_id);
create index if not exists game_stats_player_idx on public.game_stats (player_id);

alter table public.game_stats enable row level security;
create policy game_stats_read   on public.game_stats for select using (true);
create policy game_stats_insert on public.game_stats for insert with check (true);
create policy game_stats_update on public.game_stats for update using (true);
create policy game_stats_delete on public.game_stats for delete using (true);
