-- Log of GroupMe reminder posts. Mirrors sms_reminder_log, but a GroupMe
-- reminder targets a *group* rather than a phone number, and fires twice per
-- item (the night before and the morning of), so the idempotency key carries
-- both the bot it went to and which run sent it.
--
-- Without `phase` in the key the morning run would find the evening row and
-- skip, and each item would only ever be announced once.
create table if not exists public.groupme_reminder_log (
  id          integer generated by default as identity primary key,
  item_kind   text not null,            -- 'event' | 'game'
  item_id     bigint not null,
  remind_date date not null,            -- club-timezone day the reminder was FOR
  phase       text not null,            -- 'evening' (night before) | 'morning' (day of)
  bot_key     text not null,            -- team id as text, or 'all' for club-wide
  created_at  timestamptz default now(),
  unique (item_kind, item_id, remind_date, phase, bot_key)
);

-- Written only by the cron routes via the service role key; no client access.
alter table public.groupme_reminder_log enable row level security;

-- Announcements that are not daily reminders (a game flipping to cancelled or
-- postponed). Keyed without a date so a single cancellation announces once and
-- never repeats, even if an admin toggles the status back and forth.
create table if not exists public.groupme_announcement_log (
  id          integer generated by default as identity primary key,
  item_kind   text not null,
  item_id     bigint not null,
  kind        text not null,            -- 'cancelled' | 'postponed'
  bot_key     text not null,
  created_at  timestamptz default now(),
  unique (item_kind, item_id, kind, bot_key)
);

alter table public.groupme_announcement_log enable row level security;
