-- Parent/Guardian Consent & Player Medical Release (US Youth Soccer standard form).
-- One row per player-form request: admin generates it (status 'sent' + opaque token),
-- the parent opens /forms/medical/<token>, fills + signs, and it flips to 'completed'.
create table if not exists public.medical_forms (
  id            integer generated by default as identity primary key,
  player_id     bigint references public.players(id) on delete set null,
  token         text not null unique default gen_random_uuid()::text,
  status        text not null default 'sent',   -- 'sent' | 'completed'

  -- Player
  player_name   text,
  date_of_birth date,
  gender        text,
  address       text,
  city          text,
  state         text,
  zip           text,

  -- Parents
  father_name       text,
  father_home_phone text,
  father_work_phone text,
  mother_name       text,
  mother_home_phone text,
  mother_work_phone text,

  -- Emergency contacts (two)
  emergency1_name text,
  emergency1_home_phone text,
  emergency1_work_phone text,
  emergency2_name text,
  emergency2_home_phone text,
  emergency2_work_phone text,

  -- Medical
  allergies         text,
  other_conditions  text,
  physician_name    text,
  physician_home_phone text,
  physician_work_phone text,

  -- Insurance
  insurance_company text,
  insurance_phone   text,
  policy_holder     text,
  policy_number     text,
  group_number      text,
  insurance_card_front_url text,
  insurance_card_back_url  text,

  -- Consent + signature (typed digital signature, matching existing forms)
  consent_agreed  boolean default false,
  signature       text,
  signed_date     date,

  -- Delivery
  sent_to_phone text,

  season        text,
  created_by    text,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  completed_at  timestamptz
);

create index if not exists medical_forms_player_id_idx on public.medical_forms (player_id);
create index if not exists medical_forms_token_idx on public.medical_forms (token);

alter table public.medical_forms enable row level security;

-- Match existing app RLS convention (admin auth enforced at the route layer; the
-- public fill page reads/writes only via its unguessable token).
create policy medical_forms_read   on public.medical_forms for select using (true);
create policy medical_forms_insert on public.medical_forms for insert with check (true);
create policy medical_forms_update on public.medical_forms for update using (true);
create policy medical_forms_delete on public.medical_forms for delete using (true);
