-- Dues line items ("fees") and individual payments allocated to a fee.
--
-- Replaces the single-row-per-(player, season) `player_dues` aggregate, which
-- could only hold one owed amount and one paid amount per player. That model
-- had two problems the head coach hit:
--   1. The "set amount for all" quick entry OVERWROTE the season's owed amount,
--      so adding a $400 club fee after a $25 tournament fee erased the $25.
--   2. A single paid number can't say which fee a payment covered ("I received
--      $25 for Friendlies, not toward the $400 club fee").
--
-- New model: a player has many named fees; each fee accrues its own payments.
-- `player_dues` is left in place (unused by the app) so this migration is
-- non-destructive and reversible.

create table if not exists public.dues_fees (
  id          integer generated by default as identity primary key,
  player_id   bigint references public.players(id) on delete cascade,
  season      text not null,
  name        text not null,
  amount      numeric not null default 0,
  note        text,
  due_date    date,
  created_by  text,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create index if not exists dues_fees_player_idx on public.dues_fees (player_id);
create index if not exists dues_fees_season_idx on public.dues_fees (season);

create table if not exists public.dues_payments (
  id          integer generated by default as identity primary key,
  fee_id      integer references public.dues_fees(id) on delete cascade,
  amount      numeric not null default 0,
  method      text,
  paid_on     date not null default current_date,
  note        text,
  created_by  text,
  created_at  timestamptz default now()
);

create index if not exists dues_payments_fee_idx on public.dues_payments (fee_id);

-- RLS: open policies, matching the existing admin tables (see player_dues).
-- NOTE: this is financial PII and should be hardened to authenticated /
-- role-based access alongside the other open-RLS admin tables (tracked debt).
alter table public.dues_fees enable row level security;
create policy dues_fees_read   on public.dues_fees for select using (true);
create policy dues_fees_insert on public.dues_fees for insert with check (true);
create policy dues_fees_update on public.dues_fees for update using (true);
create policy dues_fees_delete on public.dues_fees for delete using (true);

alter table public.dues_payments enable row level security;
create policy dues_payments_read   on public.dues_payments for select using (true);
create policy dues_payments_insert on public.dues_payments for insert with check (true);
create policy dues_payments_update on public.dues_payments for update using (true);
create policy dues_payments_delete on public.dues_payments for delete using (true);

-- Migrate existing player_dues into a single "Season Dues" fee per player,
-- carrying any recorded payment across as one payment record. player_dues has
-- a unique (player_id, season) constraint, so the join below is 1:1.
with migrated as (
  insert into public.dues_fees (player_id, season, name, amount, note, due_date, created_by, created_at)
  select player_id, season, 'Season Dues', coalesce(amount_owed, 0), note, due_date, created_by, coalesce(created_at, now())
  from public.player_dues
  where coalesce(amount_owed, 0) > 0 or coalesce(amount_paid, 0) > 0
  returning id, player_id, season
)
insert into public.dues_payments (fee_id, amount, method, paid_on, note, created_by)
select m.id, pd.amount_paid, pd.payment_method,
       coalesce(pd.updated_at::date, current_date),
       'Migrated from prior dues total', pd.created_by
from migrated m
join public.player_dues pd
  on pd.player_id = m.player_id and pd.season = m.season
where coalesce(pd.amount_paid, 0) > 0;
