-- Every message the GroupMe bots actually send, with the text as posted.
--
-- Distinct from groupme_reminder_log / groupme_announcement_log: those hold one
-- bare row per (item, date, group) purely so a retry doesn't double-post. They
-- answer "has this been sent?". This table answers "what did the bots say, to
-- whom, and did it land?" — the audit trail a coach reads.
--
-- Failed sends are recorded too (ok = false, with the error), because a silent
-- gap in a chat is exactly the thing you need this log to explain.
create table if not exists public.groupme_activity_log (
  id          integer generated by default as identity primary key,
  kind        text not null,            -- 'reminder' | 'cancellation' | 'command_reply' | 'test'
  bot_key     text not null,            -- team id as text, or 'all'
  team_id     bigint,                   -- null for club-wide groups
  item_kind   text,                     -- 'event' | 'game'; null for command replies
  item_id     bigint,
  message     text not null,            -- exactly what was posted
  ok          boolean not null default true,
  error       text,
  created_at  timestamptz default now()
);

create index if not exists groupme_activity_log_created_idx
  on public.groupme_activity_log (created_at desc);

-- Written only by server routes via the service role key. Enabling RLS with no
-- policies makes it default-deny for anon/authenticated clients; the admin UI
-- reads it through a service-role API route, never directly from the browser.
alter table public.groupme_activity_log enable row level security;
