-- Links a parent account (auth user) to a player on the roster. Parent contact
-- is denormalized here so the coach's parent directory is queryable without
-- touching auth.users. A parent may link multiple children (siblings across
-- U11/U12); each link is approved by an admin.
create table if not exists public.parent_children (
  id             integer generated by default as identity primary key,
  parent_user_id uuid,
  parent_name    text,
  parent_email   text,
  parent_phone   text,
  player_id      bigint references public.players(id) on delete cascade,
  child_photo_url text,
  status         text not null default 'pending',   -- 'pending' | 'approved' | 'rejected'
  created_at     timestamptz default now(),
  approved_at    timestamptz,
  approved_by    text,
  unique (parent_user_id, player_id)
);

create index if not exists parent_children_parent_idx on public.parent_children (parent_user_id);
create index if not exists parent_children_player_idx on public.parent_children (player_id);

alter table public.parent_children enable row level security;
create policy parent_children_read   on public.parent_children for select using (true);
create policy parent_children_insert on public.parent_children for insert with check (true);
create policy parent_children_update on public.parent_children for update using (true);
create policy parent_children_delete on public.parent_children for delete using (true);
