-- Maps a GroupMe group member to who they are on the roster.
--
-- GroupMe's event RSVPs come back as bare user ids ("going": ["5832271", …])
-- and its member payload exposes only user_id, nickname and name — no email,
-- no phone, nothing that joins to parent_children. So there is no automatic
-- key, and the mapping has to be recorded once by a human.
--
-- Group members are *parents*, not players, so a mapping resolves in one of
-- two ways:
--   parent_user_id  → the RSVP applies to every approved child of that parent
--   player_id       → the RSVP applies to that one player (for a member with
--                     no parent account in the app)
-- Exactly one should be set. `ignored` covers coaches, admins and anyone else
-- in the chat with no child on the roster, so they stop showing as unmapped.
create table if not exists public.groupme_member_map (
  id                integer generated by default as identity primary key,
  groupme_user_id   text not null unique,
  -- Snapshot of the display name, so the admin list stays readable even if
  -- someone changes their GroupMe nickname later.
  groupme_name      text,
  parent_user_id    uuid,
  player_id         bigint references public.players(id) on delete cascade,
  ignored           boolean not null default false,
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

create index if not exists groupme_member_map_parent_idx on public.groupme_member_map (parent_user_id);
create index if not exists groupme_member_map_player_idx on public.groupme_member_map (player_id);

-- Written only by the admin API via the service role key; no client access.
alter table public.groupme_member_map enable row level security;
