-- Per-player, per-season dues. One row per (player, season); amount_owed folds
-- in all charges for the season and amount_paid accumulates payments.
create table if not exists public.player_dues (
  id             integer generated by default as identity primary key,
  player_id      bigint references public.players(id) on delete cascade,
  season         text not null,
  amount_owed    numeric not null default 0,
  amount_paid    numeric not null default 0,
  payment_method text,
  note           text,
  due_date       date,
  created_by     text,
  created_at     timestamptz default now(),
  updated_at     timestamptz default now(),
  unique (player_id, season)
);

create index if not exists player_dues_player_idx on public.player_dues (player_id);
create index if not exists player_dues_season_idx on public.player_dues (season);

alter table public.player_dues enable row level security;
create policy player_dues_read   on public.player_dues for select using (true);
create policy player_dues_insert on public.player_dues for insert with check (true);
create policy player_dues_update on public.player_dues for update using (true);
create policy player_dues_delete on public.player_dues for delete using (true);
