-- One row per (event, player). Separates parent intent (rsvp) from the coach's
-- recorded attendance so both can live on the same row without clobbering.
create table if not exists public.event_attendance (
  id          integer generated by default as identity primary key,
  event_id    bigint references public.events(id) on delete cascade,
  player_id   bigint references public.players(id) on delete cascade,
  rsvp        text,   -- 'going' | 'maybe' | 'not_going'  (set by parent)
  rsvp_by     text,
  attendance  text,   -- 'present' | 'absent' | 'late' | 'excused'  (set by coach)
  marked_by   text,
  note        text,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now(),
  unique (event_id, player_id)
);

create index if not exists event_attendance_event_idx on public.event_attendance (event_id);
create index if not exists event_attendance_player_idx on public.event_attendance (player_id);

alter table public.event_attendance enable row level security;
create policy event_attendance_read   on public.event_attendance for select using (true);
create policy event_attendance_insert on public.event_attendance for insert with check (true);
create policy event_attendance_update on public.event_attendance for update using (true);
create policy event_attendance_delete on public.event_attendance for delete using (true);
